config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root "categories#index", as: :authenticate_root
  end
 
  resources :categories, only: [:index, :new, :create] do
    resources :transactions
  end

  root "luncher#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :icon, presence: true

  belongs_to :user
  has_many :transactions

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :transaction_record, class_name: 'Transaction'
  belongs_to :category
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, :amount, presence: true

  belongs_to :category
  has_many :category_transactions
  has_many :categories, through: :category_transactions

  accepts_nested_attributes_for :categories
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories

  validates :full_name, :email, :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end
end

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show]

  def index
    @categories = current_user.categories
  end

  def show
    @transactions = @category.transactions
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/luncher_controller.rb
class LuncherController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions.order(created_at: :desc)
    @total_amount = @transactions.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.build
  end

  def create
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.build(transaction_params)
    if @transaction.save
      redirect_to category_transactions_path(@category), notice: 'Transaction created successfully.'
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/index.html.erb
<section class="min-h-screen bg-gray-200 flex flex-col justify-between items-center w-full">
  <div class="w-full">
    <div class="h-12 bg-main w-full text-white flex justify-center items-end pb-2">
      <h1 class="font-bold">CATEGORIES</h1>
    </div>
    <div class="px-4 mt-2 h-full w-full overflow-scroll">
      <% @categories.each do |category| %>
        <a href="<%= category_transactions_path(category) %>" class="block">
          <div class="flex mt-5 bg-white gap-4 rounded-sm">
            <div class="h-20 p-2">
              <%= image_tag(category.icon, class: "h-full") %>
            </div>
            <div class="flex items-center w-4/6 justify-between">
              <h3><%= category.name %></h3>
              <p>Total Amount: <%= category.total_amount %> </p>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
  <div class="bg-mygreen flex justify-center h-20 rounded-sm text-center w-full py-4 px-4 text-white">
    <div class="border border-2 border-white h-full w-full flex items-center justify-center">
      <%= link_to "Add a new category", new_category_path, class: "btn btn-primary" %>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<section class="min-h-screen bg-gray-200 flex flex-col items-center w-full">
  <div class="bg-main w-full text-white pt-2">
    <%= link_to root_path, class: "text-white ps-3" do %>
      <i class="fa-solid fa-arrow-left fa-lg"></i>
    <% end %>
    <div class="h-10 bg-main w-full text-white flex justify-center items-end pb-2">
      <h1 class="font-bold">Add a new category</h1>
    </div>
  </div>
  <div class="mt-4 w-full flex flex-col justify-center">
    <%= form_with(model: @category, url: categories_path) do |form| %>
      <div class="flex flex-col gap-2 px-3">
        <%= form.text_field :name, autofocus: true, placeholder: "name", class: "px-2 py-2 w-full" %>
  
        <%= form.text_field :icon, autofocus: true, placeholder: "icon url", class: "px-2 py-2" %>
      </div>
      <div class="target bg-mygreen flex items-end h-20 rounded-sm text-center w-full py-4 px-4 text-white", style="position: fixed; bottom: 0;">
        <div class="border border-2 border-white h-full w-full flex items-center justify-center">
          <%= form.submit "Save", class: "w-full" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/categories/show.html.erb
<h1>This is show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/2a42914cf9.js" crossorigin="anonymous"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {
              main: '#3778c2',
              mygreen: '#5fb523',
              myblack: '#434b54',
            }
          }
        }
      }
    </script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? && current_page?(authenticate_root_path) %>
      <%= button_to "log out", destroy_user_session_path, method: :delete, class: "w-full text-white pe-2 font-bold flex justify-end bg-main" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/luncher/index.html.erb
<section class="h-screen">
  <div class="h-3/6 w-full flex flex-col justify-end items-center">
    <%= image_tag("logoBlack.png", class: "w-40 h-auto") %>
  </div>
  <div class="h-3/6 flex flex-col justify-end items-center">
    <div class="bg-main h-fit rounded-sm text-center w-10/12 py-1 px-4 text-white mb-2">
      <%= link_to "LOG IN", new_user_session_path %>
    </div>
    <div class="text-myblack h-11/12 mb-10 border border-1 text-center border-black-200 w-10/12 py-1 px-4 ">
      <%= link_to "SIGN UP", new_user_registration_path %>
    </div>
  </div>
</section>

app/views/transactions/index.html.erb
<section class="h-screen bg-gray-200 flex flex-col items-center w-full">
  <div class="bg-main w-full text-white pt-2">
    <%= link_to root_path, class: "text-white ps-3" do %>
      <i class="fa-solid fa-arrow-left fa-lg"></i>
    <% end %>
    <div class="h-10 bg-main w-full text-white flex justify-center items-end pb-2">
      <h1 class="font-bold">Add a new category</h1>
    </div>
  </div>
  <div class="mt-4 w-full h-full flex flex-col justify-between">
    <%= form_with(model: @category, url: categories_path) do |form| %>
        <div class="flex px-3 flex-col w-full gap-2">
          <p class="px-4 font-bold flex justify-end">Total Amount: <%= @total_amount %></p>
          <div class="bg-white">
          <div class="flex items-center">
            <div class="h-20 w-20 p-2">
              <%= image_tag(@category.icon, class: "h-full") %>
            </div>
            <h1 class="ms-4 font-bold"><%= @category.name %> Transactions</h1>
          </div>
          <table class="w-full">
            <thead>
              <tr class="flex w-full px-4 justify-between">
                <th>Date</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @transactions.each do |transaction| %>
                <tr class="flex px-4 justify-between">
                  <td><%= transaction.created_at %></td>
                  <td><%= transaction.amount %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
        </div>
        <div class="target bg-mygreen flex items-end h-20 rounded-sm text-center w-full py-4 px-4 text-white", style="position: fixed; bottom: 0;">
          <div class="border border-2 border-white h-full w-full flex items-center justify-center">
            <%= link_to "Add a New Transaction", new_category_transaction_path(@category), class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</section>

app/views/transactions/new.html.erb
<section class="min-h-screen bg-gray-200 flex flex-col items-center w-full">
  <div class="bg-main w-full text-white pt-2">
    <%= link_to category_transactions_path(@category), class: "text-white ps-3" do %>
      <i class="fa-solid fa-arrow-left fa-lg"></i>
    <% end %>
    <div class="h-10 bg-main w-full text-white flex justify-center items-end pb-2">
      <h1 class="font-bold">Add a New Transaction</h1>
    </div>
  </div>
  <div class="mt-4 px-3 w-full gap-2">
        <%= form_with(model: [@category, @transaction], url: category_transactions_path(@category)) do |f| %>
          <div class="flex flex-col">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class: "w-full px-2 py-2" %>
            
            <%= f.label :amount %>
            <%= f.number_field :amount, class: "p-2" %>

            <%= f.label :categories %>
            <%= f.text_field :category_ids, autofocus: true, class: "w-full px-2 py-2" %>
          </div>
        
          <div class="bg-main h-fit rounded-sm text-center py-3 px-4 text-white mt-4">
            <%= f.submit "Save", class: "w-full" %>
          </div>
        <% end %>
  </div>
</section>